name: Deploy React App to Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Upload build
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4